// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoonGameRev.Data;

#nullable disable

namespace MoonGameRev.Data.Migrations
{
    [DbContext(typeof(MoonGameRevDbContext))]
    [Migration("20240414161238_SeedGames")]
    partial class SeedGames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MoonGameRev.Data.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MoonGameRev.Data.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Unique identifier for the game.");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("URL of the game's cover image.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Description of the game.");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Developer of the game.");

                    b.Property<string>("GameSite")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Website of the game.");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("bit")
                        .HasComment("Specifies whether the game is released or upcoming.");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Publisher of the game.");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2")
                        .HasComment("Release date of the game.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Title of the game.");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasComment("Represents a game.");

                    b.HasData(
                        new
                        {
                            Id = new Guid("92863144-4155-4871-81a9-bff3363ad461"),
                            CoverImage = "https://gaming-cdn.com/images/products/1497/616x353/the-witcher-3-wild-hunt-game-of-the-year-edition-goty-edition-pc-game-gog-com-cover.jpg?v=1670929985",
                            Description = "An action RPG game developed and published by CD Projekt.",
                            Developer = "CD Projekt Red",
                            GameSite = "https://thewitcher.com/",
                            IsReleased = true,
                            Publisher = "CD Projekt",
                            ReleaseDate = new DateTime(2015, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = new Guid("17f14caa-f88a-414c-a23a-d0a5dd54bea0"),
                            CoverImage = "https://gaming-cdn.com/images/products/5679/616x353/red-dead-redemption-2-pc-game-rockstar-cover.jpg?v=1701275002",
                            Description = "An action-adventure game developed and published by Rockstar Games.",
                            Developer = "Rockstar Games",
                            GameSite = "https://www.rockstargames.com/reddeadredemption2/",
                            IsReleased = true,
                            Publisher = "Rockstar Games",
                            ReleaseDate = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = new Guid("890ce0cb-9b2e-4be1-b6fc-538bf0ea25d1"),
                            CoverImage = "https://gaming-cdn.com/images/products/840/616x353/cyberpunk-2077-pc-game-gog-com-cover.jpg?v=1701271565",
                            Description = "An open-world action-adventure game developed and published by CD Projekt.",
                            Developer = "CD Projekt Red",
                            GameSite = "https://www.cyberpunk.net/",
                            IsReleased = true,
                            Publisher = "CD Projekt",
                            ReleaseDate = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = new Guid("6b1572f2-19ce-4218-b6d6-6ea43fe79076"),
                            CoverImage = "https://assets.nintendo.com/image/upload/ar_16:9,c_lpad,w_656/b_white/f_auto/q_auto/ncom/software/switch/70010000024591/cdb89d91f73cecccdddc8b421a31af03473ffab2c790a4cd7a133d28538052f2",
                            Description = "Apex Legends is the award-winning, free-to-play Hero Shooter from Respawn Entertainment. Master an ever-growing roster of legendary characters with powerful abilities, and experience strategic squad play and innovative gameplay in the next evolution of Hero Shooter and Battle Royale.",
                            Developer = "Respawn",
                            GameSite = "https://www.ea.com/games/apex-legends",
                            IsReleased = true,
                            Publisher = "Electronic Arts",
                            ReleaseDate = new DateTime(2019, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Apex Legends"
                        },
                        new
                        {
                            Id = new Guid("4886a5f3-5650-4cfa-b2e4-2629c4300791"),
                            CoverImage = "https://gaming-cdn.com/images/products/4824/616x353/elden-ring-pc-game-steam-europe-cover.jpg?v=1711550841",
                            Description = "An upcoming action role-playing game developed by FromSoftware and published by Bandai Namco Entertainment.",
                            Developer = "FromSoftware",
                            GameSite = "https://en.bandainamcoent.eu/elden-ring/",
                            IsReleased = true,
                            Publisher = "Bandai Namco Entertainment",
                            ReleaseDate = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = new Guid("a942e348-2037-45e5-9a76-9b1686cfceb8"),
                            CoverImage = "https://gaming-cdn.com/images/products/6215/616x353/the-last-of-us-part-ii-pc-game-steam-cover.jpg?v=1710171908",
                            Description = "An action-adventure game developed by Naughty Dog and published by Sony Interactive Entertainment.",
                            Developer = "Naughty Dog",
                            GameSite = "https://www.naughtydog.com/blog/the_last_of_us_part_ii",
                            IsReleased = true,
                            Publisher = "Sony Interactive Entertainment",
                            ReleaseDate = new DateTime(2020, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Last of Us Part II"
                        },
                        new
                        {
                            Id = new Guid("78288ba1-8c40-40f9-ac28-8dd9e1478f1d"),
                            CoverImage = "https://gaming-cdn.com/images/products/9686/616x353/ghost-of-tsushima-director-s-cut-ps5-director-s-cut-playstation-5-game-playstation-store-europe-cover.jpg?v=1712138768",
                            Description = "An action-adventure game developed by Sucker Punch Productions and published by Sony Interactive Entertainment.",
                            Developer = "Sucker Punch Productions",
                            GameSite = "https://www.suckerpunch.com/",
                            IsReleased = true,
                            Publisher = "Sony Interactive Entertainment",
                            ReleaseDate = new DateTime(2020, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ghost of Tsushima"
                        },
                        new
                        {
                            Id = new Guid("732a5714-c92a-498e-b070-2f2f73ab9b54"),
                            CoverImage = "https://gaming-cdn.com/images/products/7325/616x353/god-of-war-pc-game-steam-cover.jpg?v=1683627071",
                            Description = "An action-adventure game developed by Santa Monica Studio and published by Sony Interactive Entertainment.",
                            Developer = "Santa Monica Studio",
                            GameSite = "https://www.playstation.com/en-us/games/god-of-war/",
                            IsReleased = true,
                            Publisher = "Sony Interactive Entertainment",
                            ReleaseDate = new DateTime(2018, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "God of War"
                        },
                        new
                        {
                            Id = new Guid("a4f5262e-e453-4a6f-86e0-ef76e9b7adac"),
                            CoverImage = "https://gaming-cdn.com/images/products/12953/616x353/marvel-s-spider-man-miles-morales-pc-game-steam-cover.jpg?v=1695136231",
                            Description = "A follow-up to Marvel's Spider-Man, featuring Miles Morales as the main protagonist.",
                            Developer = "Insomniac Games",
                            GameSite = "https://insomniac.games/game/spider-man-miles-morales/",
                            IsReleased = true,
                            Publisher = "Sony Interactive Entertainment",
                            ReleaseDate = new DateTime(2020, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Marvel's Spider-Man: Miles Morales"
                        },
                        new
                        {
                            Id = new Guid("3c3d3a42-d940-449f-b300-2e8fb03a1e1d"),
                            CoverImage = "https://gaming-cdn.com/images/products/9600/616x353/demon-s-souls-remake-edition-remake-edition-pc-game-cover.jpg?v=1678437042",
                            Description = "A remake of the 2009 PlayStation 3 game, featuring stunning graphics and improved gameplay mechanics.",
                            Developer = "Bluepoint Games",
                            GameSite = "https://www.playstation.com/en-us/games/demons-souls/",
                            IsReleased = true,
                            Publisher = "Sony Interactive Entertainment",
                            ReleaseDate = new DateTime(2020, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Demon's Souls"
                        },
                        new
                        {
                            Id = new Guid("5fd8db35-d2b6-4c20-911f-36220ce63c15"),
                            CoverImage = "https://gaming-cdn.com/images/products/9143/616x353/star-wars-jedi-survivor-pc-game-ea-app-cover.jpg?v=1705308257",
                            Description = "The story of Cal Kestis continues in Star Wars Jedi: Survivor™, a third-person, galaxy-spanning, action-adventure game from Respawn Entertainment, developed in collaboration with Lucasfilm Games. This narratively driven, single-player title picks up 5 years after the events of Star Wars Jedi: Fallen Order™ and follows Cal’s increasingly desperate fight as the galaxy descends further into darkness. ",
                            Developer = "Electronic Arts, Respawn",
                            GameSite = "https://www.ea.com/games/starwars/jedi/jedi-survivor",
                            IsReleased = true,
                            Publisher = "Electronic Arts",
                            ReleaseDate = new DateTime(2023, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars Jedi: Survivor"
                        },
                        new
                        {
                            Id = new Guid("a24ff642-1ca1-4957-bc61-ede8b42415d8"),
                            CoverImage = "https://gaming-cdn.com/images/products/15086/616x353/horizon-forbidden-west-complete-edition-complete-edition-pc-game-steam-europe-cover.jpg?v=1711041164",
                            Description = "A sequel to Horizon Zero Dawn, set in a distant future where robotic creatures roam the earth.",
                            Developer = "Guerrilla Games",
                            GameSite = "https://www.guerrilla-games.com/play/horizon",
                            IsReleased = true,
                            Publisher = "Sony Interactive Entertainment",
                            ReleaseDate = new DateTime(2022, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Horizon Forbidden West"
                        },
                        new
                        {
                            Id = new Guid("87e85407-8ca4-4692-9f98-6f6dfae20046"),
                            CoverImage = "https://gaming-cdn.com/images/products/14344/616x353/star-wars-outlaws-pc-game-cover.jpg?v=1712670300",
                            Description = "Experience the first-ever open world Star Wars game and explore distinct planets across the galaxy, both iconic and new. Risk it all as Kay Vess, an emerging scoundrel seeking freedom and the means to start a new life. Fight, steal, & outwit your way through the galaxy’s crime syndicates as you join the galaxy’s most wanted.",
                            Developer = "Massive Entertainment",
                            GameSite = "https://www.ubisoft.com/en-gb/game/star-wars/outlaws",
                            IsReleased = false,
                            Publisher = "Ubisoft",
                            ReleaseDate = new DateTime(2024, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars Outlaws"
                        },
                        new
                        {
                            Id = new Guid("a2d0e120-6821-44d9-896c-5e5a156a8fe8"),
                            CoverImage = "https://gaming-cdn.com/images/products/7911/616x353/dragon-s-dogma-2-pc-game-steam-europe-cover.jpg?v=1711626178",
                            Description = "Dragon’s Dogma is a single player, narrative driven action-RPG series that challenges the players to choose their own experience – from the appearance of their Arisen, their vocation, their party, how to approach different situations and more. Now, in this long-awaited sequel, the deep, explorable fantasy world of Dragon’s Dogma 2 awaits.",
                            Developer = "CAPCOM",
                            GameSite = "https://www.dragonsdogma.com/2/en-us/",
                            IsReleased = false,
                            Publisher = "CAPCOM",
                            ReleaseDate = new DateTime(2022, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dragon's Dogma 2"
                        },
                        new
                        {
                            Id = new Guid("ed8ff03b-952f-48ee-91be-03da616c33c2"),
                            CoverImage = "https://gaming-cdn.com/images/products/5376/616x353/s-t-a-l-k-e-r-2-heart-of-chornobyl-pc-game-steam-europe-cover.jpg?v=1709717150",
                            Description = "The game is a blend of first person shooter action, combined with an immersive simulation game and a horror game, all rolled into one and sent out into the world with an atmospheric open world for you to explore – if you are brave enough!",
                            Developer = "GSC Game World",
                            GameSite = "https://www.stalker2.com/en",
                            IsReleased = false,
                            Publisher = "GSC Game World",
                            ReleaseDate = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "S.T.A.L.K.E.R. 2: Heart of Chornobyl"
                        },
                        new
                        {
                            Id = new Guid("89b8ed61-33e7-457c-bddf-86fbed59b1c4"),
                            CoverImage = "https://gaming-cdn.com/images/products/13652/616x353/elden-ring-shadow-of-the-erdtree-pc-game-steam-europe-cover.jpg?v=1709640799",
                            Description = "Winner of hundreds of accolades including The Game Awards Game of the Year and Golden Joystick Awards Ultimate Game of the Year, ELDEN RING is the acclaimed action RPG epic set in a vast, dark fantasy world. Players embark on an epic quest with the freedom to explore and adventure at their own pace.\r\n\r\nThe Shadow of the Erdtree expansion features an all-new story set in the Land of Shadow imbued with mystery, perilous dungeons, and new enemies, weapons and equipment.",
                            Developer = "FromSoftware",
                            GameSite = "https://en.bandainamcoent.eu/elden-ring/elden-ring/shadow-of-the-erdtree",
                            IsReleased = false,
                            Publisher = "BANDAI NAMCO Entertainment",
                            ReleaseDate = new DateTime(2024, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Elden Ring - Shadow of the Erdtree"
                        });
                });

            modelBuilder.Entity("MoonGameRev.Data.Models.GameGenre", b =>
                {
                    b.Property<Guid>("GameID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.HasKey("GameID", "GenreID");

                    b.HasIndex("GenreID");

                    b.ToTable("GameGenres");
                });

            modelBuilder.Entity("MoonGameRev.Data.Models.Genre", b =>
                {
                    b.Property<int>("GenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique identifier for the genre.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the genre.");

                    b.HasKey("GenreID");

                    b.ToTable("Genres");

                    b.HasComment("Represents a genre.");

                    b.HasData(
                        new
                        {
                            GenreID = 1,
                            Name = "Adventure"
                        },
                        new
                        {
                            GenreID = 2,
                            Name = "Action"
                        },
                        new
                        {
                            GenreID = 3,
                            Name = "Sports"
                        },
                        new
                        {
                            GenreID = 4,
                            Name = "Simulation"
                        },
                        new
                        {
                            GenreID = 5,
                            Name = "Platformer"
                        },
                        new
                        {
                            GenreID = 6,
                            Name = "RPG"
                        },
                        new
                        {
                            GenreID = 7,
                            Name = "First-person shooter"
                        },
                        new
                        {
                            GenreID = 8,
                            Name = "Action-adventure"
                        },
                        new
                        {
                            GenreID = 9,
                            Name = "Fighting"
                        },
                        new
                        {
                            GenreID = 10,
                            Name = "Real-time strategy"
                        },
                        new
                        {
                            GenreID = 11,
                            Name = "Racing"
                        },
                        new
                        {
                            GenreID = 12,
                            Name = "Puzzle"
                        },
                        new
                        {
                            GenreID = 13,
                            Name = "Strategy game"
                        },
                        new
                        {
                            GenreID = 14,
                            Name = "MMO"
                        },
                        new
                        {
                            GenreID = 15,
                            Name = "Party"
                        },
                        new
                        {
                            GenreID = 16,
                            Name = "Action RPG"
                        },
                        new
                        {
                            GenreID = 17,
                            Name = "Survival"
                        },
                        new
                        {
                            GenreID = 18,
                            Name = "Third-Person Shooter"
                        },
                        new
                        {
                            GenreID = 19,
                            Name = "Casual"
                        },
                        new
                        {
                            GenreID = 20,
                            Name = "Story-Rich"
                        },
                        new
                        {
                            GenreID = 21,
                            Name = "Role-Playing"
                        },
                        new
                        {
                            GenreID = 22,
                            Name = "Building & Automation"
                        },
                        new
                        {
                            GenreID = 23,
                            Name = "Card & Board"
                        },
                        new
                        {
                            GenreID = 24,
                            Name = "Souls-Like"
                        },
                        new
                        {
                            GenreID = 25,
                            Name = "Open World"
                        },
                        new
                        {
                            GenreID = 26,
                            Name = "Third-Person"
                        });
                });

            modelBuilder.Entity("MoonGameRev.Data.Models.Journalist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Journalists");
                });

            modelBuilder.Entity("MoonGameRev.Data.Models.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("JournalistId")
                        .HasColumnType("int");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex("JournalistId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("MoonGameRev.Data.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Unique identifier for the review.");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Comment provided by the user for the review.");

                    b.Property<string>("Cons")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("The Cons of the game");

                    b.Property<Guid>("GameID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Pros")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("The Pros of the game");

                    b.Property<double>("Rating")
                        .HasColumnType("float")
                        .HasComment("Rating given by the user for the game");

                    b.Property<DateTime>("ReviewDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Date and time when the review was submitted.");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GameID");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasComment("Review for a game");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MoonGameRev.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MoonGameRev.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoonGameRev.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MoonGameRev.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MoonGameRev.Data.Models.GameGenre", b =>
                {
                    b.HasOne("MoonGameRev.Data.Models.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoonGameRev.Data.Models.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MoonGameRev.Data.Models.Journalist", b =>
                {
                    b.HasOne("MoonGameRev.Data.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoonGameRev.Data.Models.News", b =>
                {
                    b.HasOne("MoonGameRev.Data.Models.Journalist", "Journalist")
                        .WithMany("NewsArticles")
                        .HasForeignKey("JournalistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Journalist");
                });

            modelBuilder.Entity("MoonGameRev.Data.Models.Review", b =>
                {
                    b.HasOne("MoonGameRev.Data.Models.Game", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoonGameRev.Data.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoonGameRev.Data.Models.Game", b =>
                {
                    b.Navigation("GameGenres");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MoonGameRev.Data.Models.Genre", b =>
                {
                    b.Navigation("GameGenres");
                });

            modelBuilder.Entity("MoonGameRev.Data.Models.Journalist", b =>
                {
                    b.Navigation("NewsArticles");
                });
#pragma warning restore 612, 618
        }
    }
}
